syntax = "proto3";

package room;

option go_package = ".";

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";

service RoomService {
    rpc JoinRoom(JoinRoomRequest) returns (JoinRoomResponse);
    rpc RecordRoom(RecordRoomRequest) returns (google.protobuf.Empty);
    rpc StopRecording(RecordRoomRequest) returns (google.protobuf.Empty);
    rpc GetRecording(GetRecordingRequest) returns (GetRecordingResponse);
    // rpc GetRoom(GetRoomRequest) returns (Room);
}

message JoinRoomRequest {
    string meeting_id = 1 [(buf.validate.field).required = true];
}

message JoinRoomResponse {
    string token = 1;
}

message RecordRoomRequest {
    string meeting_id = 1 [(buf.validate.field).required = true];
}

message RecordRoomResponse {
    string recording_url = 1;
}

message GetRecordingRequest {
    string meeting_id = 1 [(buf.validate.field).required = true];
}

message GetRecordingResponse {
    repeated string urls = 1;
}
