// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               unknown
// source: room.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "room";

export interface JoinRoomRequest {
  meetingId: number;
}

export interface JoinRoomResponse {
  token: string;
}

function createBaseJoinRoomRequest(): JoinRoomRequest {
  return { meetingId: 0 };
}

export const JoinRoomRequest: MessageFns<JoinRoomRequest> = {
  encode(message: JoinRoomRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingId !== 0) {
      writer.uint32(8).uint32(message.meetingId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinRoomRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRoomRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.meetingId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRoomRequest {
    return { meetingId: isSet(object.meetingId) ? globalThis.Number(object.meetingId) : 0 };
  },

  toJSON(message: JoinRoomRequest): unknown {
    const obj: any = {};
    if (message.meetingId !== 0) {
      obj.meetingId = Math.round(message.meetingId);
    }
    return obj;
  },

  create(base?: DeepPartial<JoinRoomRequest>): JoinRoomRequest {
    return JoinRoomRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JoinRoomRequest>): JoinRoomRequest {
    const message = createBaseJoinRoomRequest();
    message.meetingId = object.meetingId ?? 0;
    return message;
  },
};

function createBaseJoinRoomResponse(): JoinRoomResponse {
  return { token: "" };
}

export const JoinRoomResponse: MessageFns<JoinRoomResponse> = {
  encode(message: JoinRoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinRoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRoomResponse {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: JoinRoomResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<JoinRoomResponse>): JoinRoomResponse {
    return JoinRoomResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JoinRoomResponse>): JoinRoomResponse {
    const message = createBaseJoinRoomResponse();
    message.token = object.token ?? "";
    return message;
  },
};

export type RoomServiceDefinition = typeof RoomServiceDefinition;
export const RoomServiceDefinition = {
  name: "RoomService",
  fullName: "room.RoomService",
  methods: {
    /** rpc GetRoom(GetRoomRequest) returns (Room); */
    joinRoom: {
      name: "JoinRoom",
      requestType: JoinRoomRequest,
      requestStream: false,
      responseType: JoinRoomResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface RoomServiceImplementation<CallContextExt = {}> {
  /** rpc GetRoom(GetRoomRequest) returns (Room); */
  joinRoom(request: JoinRoomRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JoinRoomResponse>>;
}

export interface RoomServiceClient<CallOptionsExt = {}> {
  /** rpc GetRoom(GetRoomRequest) returns (Room); */
  joinRoom(request: DeepPartial<JoinRoomRequest>, options?: CallOptions & CallOptionsExt): Promise<JoinRoomResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
