// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               unknown
// source: room.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "room";

export interface JoinRoomRequest {
  meetingId: string;
}

export interface JoinRoomResponse {
  token: string;
}

export interface RecordRoomRequest {
  meetingId: string;
}

export interface RecordRoomResponse {
  recordingUrl: string;
}

export interface GetRecordingRequest {
  meetingId: string;
}

export interface GetRecordingResponse {
  meetingName: string;
  meetingDescription: string;
  urls: string[];
}

export interface GenerateJoinLinkRequest {
  meetingId: string;
}

export interface GenerateJoinLinkResponse {
  token: string;
}

function createBaseJoinRoomRequest(): JoinRoomRequest {
  return { meetingId: "" };
}

export const JoinRoomRequest: MessageFns<JoinRoomRequest> = {
  encode(message: JoinRoomRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingId !== "") {
      writer.uint32(10).string(message.meetingId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinRoomRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRoomRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetingId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRoomRequest {
    return { meetingId: isSet(object.meetingId) ? globalThis.String(object.meetingId) : "" };
  },

  toJSON(message: JoinRoomRequest): unknown {
    const obj: any = {};
    if (message.meetingId !== "") {
      obj.meetingId = message.meetingId;
    }
    return obj;
  },

  create(base?: DeepPartial<JoinRoomRequest>): JoinRoomRequest {
    return JoinRoomRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JoinRoomRequest>): JoinRoomRequest {
    const message = createBaseJoinRoomRequest();
    message.meetingId = object.meetingId ?? "";
    return message;
  },
};

function createBaseJoinRoomResponse(): JoinRoomResponse {
  return { token: "" };
}

export const JoinRoomResponse: MessageFns<JoinRoomResponse> = {
  encode(message: JoinRoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinRoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRoomResponse {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: JoinRoomResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<JoinRoomResponse>): JoinRoomResponse {
    return JoinRoomResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<JoinRoomResponse>): JoinRoomResponse {
    const message = createBaseJoinRoomResponse();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseRecordRoomRequest(): RecordRoomRequest {
  return { meetingId: "" };
}

export const RecordRoomRequest: MessageFns<RecordRoomRequest> = {
  encode(message: RecordRoomRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingId !== "") {
      writer.uint32(10).string(message.meetingId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordRoomRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordRoomRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetingId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordRoomRequest {
    return { meetingId: isSet(object.meetingId) ? globalThis.String(object.meetingId) : "" };
  },

  toJSON(message: RecordRoomRequest): unknown {
    const obj: any = {};
    if (message.meetingId !== "") {
      obj.meetingId = message.meetingId;
    }
    return obj;
  },

  create(base?: DeepPartial<RecordRoomRequest>): RecordRoomRequest {
    return RecordRoomRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RecordRoomRequest>): RecordRoomRequest {
    const message = createBaseRecordRoomRequest();
    message.meetingId = object.meetingId ?? "";
    return message;
  },
};

function createBaseRecordRoomResponse(): RecordRoomResponse {
  return { recordingUrl: "" };
}

export const RecordRoomResponse: MessageFns<RecordRoomResponse> = {
  encode(message: RecordRoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recordingUrl !== "") {
      writer.uint32(10).string(message.recordingUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordRoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordRoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.recordingUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordRoomResponse {
    return { recordingUrl: isSet(object.recordingUrl) ? globalThis.String(object.recordingUrl) : "" };
  },

  toJSON(message: RecordRoomResponse): unknown {
    const obj: any = {};
    if (message.recordingUrl !== "") {
      obj.recordingUrl = message.recordingUrl;
    }
    return obj;
  },

  create(base?: DeepPartial<RecordRoomResponse>): RecordRoomResponse {
    return RecordRoomResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RecordRoomResponse>): RecordRoomResponse {
    const message = createBaseRecordRoomResponse();
    message.recordingUrl = object.recordingUrl ?? "";
    return message;
  },
};

function createBaseGetRecordingRequest(): GetRecordingRequest {
  return { meetingId: "" };
}

export const GetRecordingRequest: MessageFns<GetRecordingRequest> = {
  encode(message: GetRecordingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingId !== "") {
      writer.uint32(10).string(message.meetingId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRecordingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRecordingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetingId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRecordingRequest {
    return { meetingId: isSet(object.meetingId) ? globalThis.String(object.meetingId) : "" };
  },

  toJSON(message: GetRecordingRequest): unknown {
    const obj: any = {};
    if (message.meetingId !== "") {
      obj.meetingId = message.meetingId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetRecordingRequest>): GetRecordingRequest {
    return GetRecordingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetRecordingRequest>): GetRecordingRequest {
    const message = createBaseGetRecordingRequest();
    message.meetingId = object.meetingId ?? "";
    return message;
  },
};

function createBaseGetRecordingResponse(): GetRecordingResponse {
  return { meetingName: "", meetingDescription: "", urls: [] };
}

export const GetRecordingResponse: MessageFns<GetRecordingResponse> = {
  encode(message: GetRecordingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingName !== "") {
      writer.uint32(10).string(message.meetingName);
    }
    if (message.meetingDescription !== "") {
      writer.uint32(18).string(message.meetingDescription);
    }
    for (const v of message.urls) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRecordingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRecordingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetingName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.meetingDescription = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.urls.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRecordingResponse {
    return {
      meetingName: isSet(object.meetingName) ? globalThis.String(object.meetingName) : "",
      meetingDescription: isSet(object.meetingDescription) ? globalThis.String(object.meetingDescription) : "",
      urls: globalThis.Array.isArray(object?.urls) ? object.urls.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetRecordingResponse): unknown {
    const obj: any = {};
    if (message.meetingName !== "") {
      obj.meetingName = message.meetingName;
    }
    if (message.meetingDescription !== "") {
      obj.meetingDescription = message.meetingDescription;
    }
    if (message.urls?.length) {
      obj.urls = message.urls;
    }
    return obj;
  },

  create(base?: DeepPartial<GetRecordingResponse>): GetRecordingResponse {
    return GetRecordingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetRecordingResponse>): GetRecordingResponse {
    const message = createBaseGetRecordingResponse();
    message.meetingName = object.meetingName ?? "";
    message.meetingDescription = object.meetingDescription ?? "";
    message.urls = object.urls?.map((e) => e) || [];
    return message;
  },
};

function createBaseGenerateJoinLinkRequest(): GenerateJoinLinkRequest {
  return { meetingId: "" };
}

export const GenerateJoinLinkRequest: MessageFns<GenerateJoinLinkRequest> = {
  encode(message: GenerateJoinLinkRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meetingId !== "") {
      writer.uint32(10).string(message.meetingId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateJoinLinkRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateJoinLinkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetingId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateJoinLinkRequest {
    return { meetingId: isSet(object.meetingId) ? globalThis.String(object.meetingId) : "" };
  },

  toJSON(message: GenerateJoinLinkRequest): unknown {
    const obj: any = {};
    if (message.meetingId !== "") {
      obj.meetingId = message.meetingId;
    }
    return obj;
  },

  create(base?: DeepPartial<GenerateJoinLinkRequest>): GenerateJoinLinkRequest {
    return GenerateJoinLinkRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GenerateJoinLinkRequest>): GenerateJoinLinkRequest {
    const message = createBaseGenerateJoinLinkRequest();
    message.meetingId = object.meetingId ?? "";
    return message;
  },
};

function createBaseGenerateJoinLinkResponse(): GenerateJoinLinkResponse {
  return { token: "" };
}

export const GenerateJoinLinkResponse: MessageFns<GenerateJoinLinkResponse> = {
  encode(message: GenerateJoinLinkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateJoinLinkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateJoinLinkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateJoinLinkResponse {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: GenerateJoinLinkResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<GenerateJoinLinkResponse>): GenerateJoinLinkResponse {
    return GenerateJoinLinkResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GenerateJoinLinkResponse>): GenerateJoinLinkResponse {
    const message = createBaseGenerateJoinLinkResponse();
    message.token = object.token ?? "";
    return message;
  },
};

export type RoomServiceDefinition = typeof RoomServiceDefinition;
export const RoomServiceDefinition = {
  name: "RoomService",
  fullName: "room.RoomService",
  methods: {
    joinRoom: {
      name: "JoinRoom",
      requestType: JoinRoomRequest,
      requestStream: false,
      responseType: JoinRoomResponse,
      responseStream: false,
      options: {},
    },
    recordRoom: {
      name: "RecordRoom",
      requestType: RecordRoomRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    stopRecording: {
      name: "StopRecording",
      requestType: RecordRoomRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    getRecording: {
      name: "GetRecording",
      requestType: GetRecordingRequest,
      requestStream: false,
      responseType: GetRecordingResponse,
      responseStream: false,
      options: {},
    },
    /** rpc GetRoom(GetRoomRequest) returns (Room); */
    generateGuestJoinRoomToken: {
      name: "GenerateGuestJoinRoomToken",
      requestType: GenerateJoinLinkRequest,
      requestStream: false,
      responseType: GenerateJoinLinkResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface RoomServiceImplementation<CallContextExt = {}> {
  joinRoom(request: JoinRoomRequest, context: CallContext & CallContextExt): Promise<DeepPartial<JoinRoomResponse>>;
  recordRoom(request: RecordRoomRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  stopRecording(request: RecordRoomRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  getRecording(
    request: GetRecordingRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetRecordingResponse>>;
  /** rpc GetRoom(GetRoomRequest) returns (Room); */
  generateGuestJoinRoomToken(
    request: GenerateJoinLinkRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GenerateJoinLinkResponse>>;
}

export interface RoomServiceClient<CallOptionsExt = {}> {
  joinRoom(request: DeepPartial<JoinRoomRequest>, options?: CallOptions & CallOptionsExt): Promise<JoinRoomResponse>;
  recordRoom(request: DeepPartial<RecordRoomRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  stopRecording(request: DeepPartial<RecordRoomRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  getRecording(
    request: DeepPartial<GetRecordingRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetRecordingResponse>;
  /** rpc GetRoom(GetRoomRequest) returns (Room); */
  generateGuestJoinRoomToken(
    request: DeepPartial<GenerateJoinLinkRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GenerateJoinLinkResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
