/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: schedule.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./buf\\validate\\validate";
import * as dependency_2 from "./google\\protobuf\\timestamp";
import * as dependency_3 from "./google\\protobuf\\empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace schedule {
    export enum MeetingType {
        VIDEO = 0,
        AUDIO = 1
    }
    export class Meeting extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            title?: string;
            description?: string;
            type?: MeetingType;
            start_time?: dependency_2.google.protobuf.Timestamp;
            participants_count?: number;
            host?: MeetParticipant;
            is_cancelled?: boolean;
            first_three_participants?: MeetParticipant[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [9], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("start_time" in data && data.start_time != undefined) {
                    this.start_time = data.start_time;
                }
                if ("participants_count" in data && data.participants_count != undefined) {
                    this.participants_count = data.participants_count;
                }
                if ("host" in data && data.host != undefined) {
                    this.host = data.host;
                }
                if ("is_cancelled" in data && data.is_cancelled != undefined) {
                    this.is_cancelled = data.is_cancelled;
                }
                if ("first_three_participants" in data && data.first_three_participants != undefined) {
                    this.first_three_participants = data.first_three_participants;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get title() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set title(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get description() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set description(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 4, MeetingType.VIDEO) as MeetingType;
        }
        set type(value: MeetingType) {
            pb_1.Message.setField(this, 4, value);
        }
        get start_time() {
            return pb_1.Message.getWrapperField(this, dependency_2.google.protobuf.Timestamp, 5) as dependency_2.google.protobuf.Timestamp;
        }
        set start_time(value: dependency_2.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 5, value);
        }
        get has_start_time() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get participants_count() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set participants_count(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get host() {
            return pb_1.Message.getWrapperField(this, MeetParticipant, 7) as MeetParticipant;
        }
        set host(value: MeetParticipant) {
            pb_1.Message.setWrapperField(this, 7, value);
        }
        get has_host() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get is_cancelled() {
            return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
        }
        set is_cancelled(value: boolean) {
            pb_1.Message.setField(this, 8, value);
        }
        get first_three_participants() {
            return pb_1.Message.getRepeatedWrapperField(this, MeetParticipant, 9) as MeetParticipant[];
        }
        set first_three_participants(value: MeetParticipant[]) {
            pb_1.Message.setRepeatedWrapperField(this, 9, value);
        }
        static fromObject(data: {
            id?: number;
            title?: string;
            description?: string;
            type?: MeetingType;
            start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
            participants_count?: number;
            host?: ReturnType<typeof MeetParticipant.prototype.toObject>;
            is_cancelled?: boolean;
            first_three_participants?: ReturnType<typeof MeetParticipant.prototype.toObject>[];
        }): Meeting {
            const message = new Meeting({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.description != null) {
                message.description = data.description;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.start_time != null) {
                message.start_time = dependency_2.google.protobuf.Timestamp.fromObject(data.start_time);
            }
            if (data.participants_count != null) {
                message.participants_count = data.participants_count;
            }
            if (data.host != null) {
                message.host = MeetParticipant.fromObject(data.host);
            }
            if (data.is_cancelled != null) {
                message.is_cancelled = data.is_cancelled;
            }
            if (data.first_three_participants != null) {
                message.first_three_participants = data.first_three_participants.map(item => MeetParticipant.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                title?: string;
                description?: string;
                type?: MeetingType;
                start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
                participants_count?: number;
                host?: ReturnType<typeof MeetParticipant.prototype.toObject>;
                is_cancelled?: boolean;
                first_three_participants?: ReturnType<typeof MeetParticipant.prototype.toObject>[];
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.description != null) {
                data.description = this.description;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.start_time != null) {
                data.start_time = this.start_time.toObject();
            }
            if (this.participants_count != null) {
                data.participants_count = this.participants_count;
            }
            if (this.host != null) {
                data.host = this.host.toObject();
            }
            if (this.is_cancelled != null) {
                data.is_cancelled = this.is_cancelled;
            }
            if (this.first_three_participants != null) {
                data.first_three_participants = this.first_three_participants.map((item: MeetParticipant) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeUint32(1, this.id);
            if (this.title.length)
                writer.writeString(2, this.title);
            if (this.description.length)
                writer.writeString(3, this.description);
            if (this.type != MeetingType.VIDEO)
                writer.writeEnum(4, this.type);
            if (this.has_start_time)
                writer.writeMessage(5, this.start_time, () => this.start_time.serialize(writer));
            if (this.participants_count != 0)
                writer.writeUint32(6, this.participants_count);
            if (this.has_host)
                writer.writeMessage(7, this.host, () => this.host.serialize(writer));
            if (this.is_cancelled != false)
                writer.writeBool(8, this.is_cancelled);
            if (this.first_three_participants.length)
                writer.writeRepeatedMessage(9, this.first_three_participants, (item: MeetParticipant) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Meeting {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Meeting();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readUint32();
                        break;
                    case 2:
                        message.title = reader.readString();
                        break;
                    case 3:
                        message.description = reader.readString();
                        break;
                    case 4:
                        message.type = reader.readEnum();
                        break;
                    case 5:
                        reader.readMessage(message.start_time, () => message.start_time = dependency_2.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 6:
                        message.participants_count = reader.readUint32();
                        break;
                    case 7:
                        reader.readMessage(message.host, () => message.host = MeetParticipant.deserialize(reader));
                        break;
                    case 8:
                        message.is_cancelled = reader.readBool();
                        break;
                    case 9:
                        reader.readMessage(message.first_three_participants, () => pb_1.Message.addToRepeatedWrapperField(message, 9, MeetParticipant.deserialize(reader), MeetParticipant));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Meeting {
            return Meeting.deserialize(bytes);
        }
    }
    export class MeetParticipant extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            avatar_url?: string;
            name?: string;
            email?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("avatar_url" in data && data.avatar_url != undefined) {
                    this.avatar_url = data.avatar_url;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get avatar_url() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set avatar_url(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            id?: string;
            avatar_url?: string;
            name?: string;
            email?: string;
        }): MeetParticipant {
            const message = new MeetParticipant({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.avatar_url != null) {
                message.avatar_url = data.avatar_url;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                avatar_url?: string;
                name?: string;
                email?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.avatar_url != null) {
                data.avatar_url = this.avatar_url;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(2, this.id);
            if (this.avatar_url.length)
                writer.writeString(3, this.avatar_url);
            if (this.name.length)
                writer.writeString(4, this.name);
            if (this.email.length)
                writer.writeString(5, this.email);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MeetParticipant {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MeetParticipant();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 2:
                        message.id = reader.readString();
                        break;
                    case 3:
                        message.avatar_url = reader.readString();
                        break;
                    case 4:
                        message.name = reader.readString();
                        break;
                    case 5:
                        message.email = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MeetParticipant {
            return MeetParticipant.deserialize(bytes);
        }
    }
    export class CreateMeetingRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            title?: string;
            description?: string;
            start_time?: dependency_2.google.protobuf.Timestamp;
            type?: MeetingType;
            participant_ids?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [5], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
                if ("start_time" in data && data.start_time != undefined) {
                    this.start_time = data.start_time;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("participant_ids" in data && data.participant_ids != undefined) {
                    this.participant_ids = data.participant_ids;
                }
            }
        }
        get title() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set title(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get description() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set description(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get start_time() {
            return pb_1.Message.getWrapperField(this, dependency_2.google.protobuf.Timestamp, 3) as dependency_2.google.protobuf.Timestamp;
        }
        set start_time(value: dependency_2.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_start_time() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 4, MeetingType.VIDEO) as MeetingType;
        }
        set type(value: MeetingType) {
            pb_1.Message.setField(this, 4, value);
        }
        get participant_ids() {
            return pb_1.Message.getFieldWithDefault(this, 5, []) as string[];
        }
        set participant_ids(value: string[]) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            title?: string;
            description?: string;
            start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
            type?: MeetingType;
            participant_ids?: string[];
        }): CreateMeetingRequest {
            const message = new CreateMeetingRequest({});
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.description != null) {
                message.description = data.description;
            }
            if (data.start_time != null) {
                message.start_time = dependency_2.google.protobuf.Timestamp.fromObject(data.start_time);
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.participant_ids != null) {
                message.participant_ids = data.participant_ids;
            }
            return message;
        }
        toObject() {
            const data: {
                title?: string;
                description?: string;
                start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
                type?: MeetingType;
                participant_ids?: string[];
            } = {};
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.description != null) {
                data.description = this.description;
            }
            if (this.start_time != null) {
                data.start_time = this.start_time.toObject();
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.participant_ids != null) {
                data.participant_ids = this.participant_ids;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.title.length)
                writer.writeString(1, this.title);
            if (this.description.length)
                writer.writeString(2, this.description);
            if (this.has_start_time)
                writer.writeMessage(3, this.start_time, () => this.start_time.serialize(writer));
            if (this.type != MeetingType.VIDEO)
                writer.writeEnum(4, this.type);
            if (this.participant_ids.length)
                writer.writeRepeatedString(5, this.participant_ids);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateMeetingRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateMeetingRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.title = reader.readString();
                        break;
                    case 2:
                        message.description = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.start_time, () => message.start_time = dependency_2.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 4:
                        message.type = reader.readEnum();
                        break;
                    case 5:
                        pb_1.Message.addToRepeatedField(message, 5, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateMeetingRequest {
            return CreateMeetingRequest.deserialize(bytes);
        }
    }
    export class UpdateMeetingRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[2], [3], [4], [5], [8]];
        constructor(data?: any[] | ({
            id?: number;
            isParticipantIdsEmpty?: boolean;
            participant_ids?: string[];
        } & (({
            title?: string;
        }) | ({
            description?: string;
        }) | ({
            start_time?: dependency_2.google.protobuf.Timestamp;
        }) | ({
            type?: MeetingType;
        }) | ({
            is_cancelled?: boolean;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
                if ("start_time" in data && data.start_time != undefined) {
                    this.start_time = data.start_time;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("isParticipantIdsEmpty" in data && data.isParticipantIdsEmpty != undefined) {
                    this.isParticipantIdsEmpty = data.isParticipantIdsEmpty;
                }
                if ("participant_ids" in data && data.participant_ids != undefined) {
                    this.participant_ids = data.participant_ids;
                }
                if ("is_cancelled" in data && data.is_cancelled != undefined) {
                    this.is_cancelled = data.is_cancelled;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get title() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set title(value: string) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_title() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get description() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set description(value: string) {
            pb_1.Message.setOneofField(this, 3, this.#one_of_decls[1], value);
        }
        get has_description() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get start_time() {
            return pb_1.Message.getWrapperField(this, dependency_2.google.protobuf.Timestamp, 4) as dependency_2.google.protobuf.Timestamp;
        }
        set start_time(value: dependency_2.google.protobuf.Timestamp) {
            pb_1.Message.setOneofWrapperField(this, 4, this.#one_of_decls[2], value);
        }
        get has_start_time() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 5, MeetingType.VIDEO) as MeetingType;
        }
        set type(value: MeetingType) {
            pb_1.Message.setOneofField(this, 5, this.#one_of_decls[3], value);
        }
        get has_type() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get isParticipantIdsEmpty() {
            return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
        }
        set isParticipantIdsEmpty(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        get participant_ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set participant_ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get is_cancelled() {
            return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
        }
        set is_cancelled(value: boolean) {
            pb_1.Message.setOneofField(this, 8, this.#one_of_decls[4], value);
        }
        get has_is_cancelled() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get _title() {
            const cases: {
                [index: number]: "none" | "title";
            } = {
                0: "none",
                2: "title"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        get _description() {
            const cases: {
                [index: number]: "none" | "description";
            } = {
                0: "none",
                3: "description"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        get _start_time() {
            const cases: {
                [index: number]: "none" | "start_time";
            } = {
                0: "none",
                4: "start_time"
            };
            return cases[pb_1.Message.computeOneofCase(this, [4])];
        }
        get _type() {
            const cases: {
                [index: number]: "none" | "type";
            } = {
                0: "none",
                5: "type"
            };
            return cases[pb_1.Message.computeOneofCase(this, [5])];
        }
        get _is_cancelled() {
            const cases: {
                [index: number]: "none" | "is_cancelled";
            } = {
                0: "none",
                8: "is_cancelled"
            };
            return cases[pb_1.Message.computeOneofCase(this, [8])];
        }
        static fromObject(data: {
            id?: number;
            title?: string;
            description?: string;
            start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
            type?: MeetingType;
            isParticipantIdsEmpty?: boolean;
            participant_ids?: string[];
            is_cancelled?: boolean;
        }): UpdateMeetingRequest {
            const message = new UpdateMeetingRequest({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.description != null) {
                message.description = data.description;
            }
            if (data.start_time != null) {
                message.start_time = dependency_2.google.protobuf.Timestamp.fromObject(data.start_time);
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.isParticipantIdsEmpty != null) {
                message.isParticipantIdsEmpty = data.isParticipantIdsEmpty;
            }
            if (data.participant_ids != null) {
                message.participant_ids = data.participant_ids;
            }
            if (data.is_cancelled != null) {
                message.is_cancelled = data.is_cancelled;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                title?: string;
                description?: string;
                start_time?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
                type?: MeetingType;
                isParticipantIdsEmpty?: boolean;
                participant_ids?: string[];
                is_cancelled?: boolean;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.description != null) {
                data.description = this.description;
            }
            if (this.start_time != null) {
                data.start_time = this.start_time.toObject();
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.isParticipantIdsEmpty != null) {
                data.isParticipantIdsEmpty = this.isParticipantIdsEmpty;
            }
            if (this.participant_ids != null) {
                data.participant_ids = this.participant_ids;
            }
            if (this.is_cancelled != null) {
                data.is_cancelled = this.is_cancelled;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeUint32(1, this.id);
            if (this.has_title)
                writer.writeString(2, this.title);
            if (this.has_description)
                writer.writeString(3, this.description);
            if (this.has_start_time)
                writer.writeMessage(4, this.start_time, () => this.start_time.serialize(writer));
            if (this.has_type)
                writer.writeEnum(5, this.type);
            if (this.isParticipantIdsEmpty != false)
                writer.writeBool(6, this.isParticipantIdsEmpty);
            if (this.participant_ids.length)
                writer.writeRepeatedString(7, this.participant_ids);
            if (this.has_is_cancelled)
                writer.writeBool(8, this.is_cancelled);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateMeetingRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateMeetingRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readUint32();
                        break;
                    case 2:
                        message.title = reader.readString();
                        break;
                    case 3:
                        message.description = reader.readString();
                        break;
                    case 4:
                        reader.readMessage(message.start_time, () => message.start_time = dependency_2.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 5:
                        message.type = reader.readEnum();
                        break;
                    case 6:
                        message.isParticipantIdsEmpty = reader.readBool();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        message.is_cancelled = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UpdateMeetingRequest {
            return UpdateMeetingRequest.deserialize(bytes);
        }
    }
    export class UpdateMeetingResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            meeting?: Meeting;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("meeting" in data && data.meeting != undefined) {
                    this.meeting = data.meeting;
                }
            }
        }
        get meeting() {
            return pb_1.Message.getWrapperField(this, Meeting, 1) as Meeting;
        }
        set meeting(value: Meeting) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_meeting() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            meeting?: ReturnType<typeof Meeting.prototype.toObject>;
        }): UpdateMeetingResponse {
            const message = new UpdateMeetingResponse({});
            if (data.meeting != null) {
                message.meeting = Meeting.fromObject(data.meeting);
            }
            return message;
        }
        toObject() {
            const data: {
                meeting?: ReturnType<typeof Meeting.prototype.toObject>;
            } = {};
            if (this.meeting != null) {
                data.meeting = this.meeting.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_meeting)
                writer.writeMessage(1, this.meeting, () => this.meeting.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateMeetingResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateMeetingResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.meeting, () => message.meeting = Meeting.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UpdateMeetingResponse {
            return UpdateMeetingResponse.deserialize(bytes);
        }
    }
    export class SearchMeetingsRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[5]];
        constructor(data?: any[] | ({
            query?: string;
            category?: SearchMeetingsRequest.MeetingCategory;
            page_size?: number;
        } & (({
            last_id?: number;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("query" in data && data.query != undefined) {
                    this.query = data.query;
                }
                if ("category" in data && data.category != undefined) {
                    this.category = data.category;
                }
                if ("last_id" in data && data.last_id != undefined) {
                    this.last_id = data.last_id;
                }
                if ("page_size" in data && data.page_size != undefined) {
                    this.page_size = data.page_size;
                }
            }
        }
        get query() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set query(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get category() {
            return pb_1.Message.getFieldWithDefault(this, 4, SearchMeetingsRequest.MeetingCategory.ALL) as SearchMeetingsRequest.MeetingCategory;
        }
        set category(value: SearchMeetingsRequest.MeetingCategory) {
            pb_1.Message.setField(this, 4, value);
        }
        get last_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set last_id(value: number) {
            pb_1.Message.setOneofField(this, 5, this.#one_of_decls[0], value);
        }
        get has_last_id() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get page_size() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set page_size(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get _last_id() {
            const cases: {
                [index: number]: "none" | "last_id";
            } = {
                0: "none",
                5: "last_id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [5])];
        }
        static fromObject(data: {
            query?: string;
            category?: SearchMeetingsRequest.MeetingCategory;
            last_id?: number;
            page_size?: number;
        }): SearchMeetingsRequest {
            const message = new SearchMeetingsRequest({});
            if (data.query != null) {
                message.query = data.query;
            }
            if (data.category != null) {
                message.category = data.category;
            }
            if (data.last_id != null) {
                message.last_id = data.last_id;
            }
            if (data.page_size != null) {
                message.page_size = data.page_size;
            }
            return message;
        }
        toObject() {
            const data: {
                query?: string;
                category?: SearchMeetingsRequest.MeetingCategory;
                last_id?: number;
                page_size?: number;
            } = {};
            if (this.query != null) {
                data.query = this.query;
            }
            if (this.category != null) {
                data.category = this.category;
            }
            if (this.last_id != null) {
                data.last_id = this.last_id;
            }
            if (this.page_size != null) {
                data.page_size = this.page_size;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.query.length)
                writer.writeString(1, this.query);
            if (this.category != SearchMeetingsRequest.MeetingCategory.ALL)
                writer.writeEnum(4, this.category);
            if (this.has_last_id)
                writer.writeUint32(5, this.last_id);
            if (this.page_size != 0)
                writer.writeUint32(6, this.page_size);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SearchMeetingsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SearchMeetingsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.query = reader.readString();
                        break;
                    case 4:
                        message.category = reader.readEnum();
                        break;
                    case 5:
                        message.last_id = reader.readUint32();
                        break;
                    case 6:
                        message.page_size = reader.readUint32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SearchMeetingsRequest {
            return SearchMeetingsRequest.deserialize(bytes);
        }
    }
    export namespace SearchMeetingsRequest {
        export enum MeetingCategory {
            ALL = 0,
            PASSED = 1,
            UPCOMING = 2
        }
    }
    export class SearchMeetingsResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            meetings?: Meeting[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("meetings" in data && data.meetings != undefined) {
                    this.meetings = data.meetings;
                }
            }
        }
        get meetings() {
            return pb_1.Message.getRepeatedWrapperField(this, Meeting, 1) as Meeting[];
        }
        set meetings(value: Meeting[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            meetings?: ReturnType<typeof Meeting.prototype.toObject>[];
        }): SearchMeetingsResponse {
            const message = new SearchMeetingsResponse({});
            if (data.meetings != null) {
                message.meetings = data.meetings.map(item => Meeting.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                meetings?: ReturnType<typeof Meeting.prototype.toObject>[];
            } = {};
            if (this.meetings != null) {
                data.meetings = this.meetings.map((item: Meeting) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.meetings.length)
                writer.writeRepeatedMessage(1, this.meetings, (item: Meeting) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SearchMeetingsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SearchMeetingsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.meetings, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Meeting.deserialize(reader), Meeting));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SearchMeetingsResponse {
            return SearchMeetingsResponse.deserialize(bytes);
        }
    }
    export class SearchParticipantsRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[2]];
        constructor(data?: any[] | ({
            emailQuery?: string;
            page_size?: number;
        } & (({
            last_id?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("emailQuery" in data && data.emailQuery != undefined) {
                    this.emailQuery = data.emailQuery;
                }
                if ("last_id" in data && data.last_id != undefined) {
                    this.last_id = data.last_id;
                }
                if ("page_size" in data && data.page_size != undefined) {
                    this.page_size = data.page_size;
                }
            }
        }
        get emailQuery() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set emailQuery(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get last_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set last_id(value: string) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_last_id() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get page_size() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set page_size(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get _last_id() {
            const cases: {
                [index: number]: "none" | "last_id";
            } = {
                0: "none",
                2: "last_id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            emailQuery?: string;
            last_id?: string;
            page_size?: number;
        }): SearchParticipantsRequest {
            const message = new SearchParticipantsRequest({});
            if (data.emailQuery != null) {
                message.emailQuery = data.emailQuery;
            }
            if (data.last_id != null) {
                message.last_id = data.last_id;
            }
            if (data.page_size != null) {
                message.page_size = data.page_size;
            }
            return message;
        }
        toObject() {
            const data: {
                emailQuery?: string;
                last_id?: string;
                page_size?: number;
            } = {};
            if (this.emailQuery != null) {
                data.emailQuery = this.emailQuery;
            }
            if (this.last_id != null) {
                data.last_id = this.last_id;
            }
            if (this.page_size != null) {
                data.page_size = this.page_size;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.emailQuery.length)
                writer.writeString(1, this.emailQuery);
            if (this.has_last_id)
                writer.writeString(2, this.last_id);
            if (this.page_size != 0)
                writer.writeUint32(3, this.page_size);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SearchParticipantsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SearchParticipantsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.emailQuery = reader.readString();
                        break;
                    case 2:
                        message.last_id = reader.readString();
                        break;
                    case 3:
                        message.page_size = reader.readUint32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SearchParticipantsRequest {
            return SearchParticipantsRequest.deserialize(bytes);
        }
    }
    export class SearchParticipantsResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            participants?: MeetParticipant[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("participants" in data && data.participants != undefined) {
                    this.participants = data.participants;
                }
            }
        }
        get participants() {
            return pb_1.Message.getRepeatedWrapperField(this, MeetParticipant, 1) as MeetParticipant[];
        }
        set participants(value: MeetParticipant[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            participants?: ReturnType<typeof MeetParticipant.prototype.toObject>[];
        }): SearchParticipantsResponse {
            const message = new SearchParticipantsResponse({});
            if (data.participants != null) {
                message.participants = data.participants.map(item => MeetParticipant.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                participants?: ReturnType<typeof MeetParticipant.prototype.toObject>[];
            } = {};
            if (this.participants != null) {
                data.participants = this.participants.map((item: MeetParticipant) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.participants.length)
                writer.writeRepeatedMessage(1, this.participants, (item: MeetParticipant) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SearchParticipantsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SearchParticipantsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.participants, () => pb_1.Message.addToRepeatedWrapperField(message, 1, MeetParticipant.deserialize(reader), MeetParticipant));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SearchParticipantsResponse {
            return SearchParticipantsResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedScheduleServiceService {
        static definition = {
            CreateMeeting: {
                path: "/schedule.ScheduleService/CreateMeeting",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: CreateMeetingRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => CreateMeetingRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            UpdateMeeting: {
                path: "/schedule.ScheduleService/UpdateMeeting",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: UpdateMeetingRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => UpdateMeetingRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            SearchMeetings: {
                path: "/schedule.ScheduleService/SearchMeetings",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SearchMeetingsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SearchMeetingsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: SearchMeetingsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => SearchMeetingsResponse.deserialize(new Uint8Array(bytes))
            },
            SearchParticipants: {
                path: "/schedule.ScheduleService/SearchParticipants",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SearchParticipantsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SearchParticipantsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: SearchParticipantsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => SearchParticipantsResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CreateMeeting(call: grpc_1.ServerUnaryCall<CreateMeetingRequest, dependency_3.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_3.google.protobuf.Empty>): void;
        abstract UpdateMeeting(call: grpc_1.ServerUnaryCall<UpdateMeetingRequest, dependency_3.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_3.google.protobuf.Empty>): void;
        abstract SearchMeetings(call: grpc_1.ServerUnaryCall<SearchMeetingsRequest, SearchMeetingsResponse>, callback: grpc_1.sendUnaryData<SearchMeetingsResponse>): void;
        abstract SearchParticipants(call: grpc_1.ServerUnaryCall<SearchParticipantsRequest, SearchParticipantsResponse>, callback: grpc_1.sendUnaryData<SearchParticipantsResponse>): void;
    }
    export class ScheduleServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedScheduleServiceService.definition, "ScheduleService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CreateMeeting: GrpcUnaryServiceInterface<CreateMeetingRequest, dependency_3.google.protobuf.Empty> = (message: CreateMeetingRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_3.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.CreateMeeting(message, metadata, options, callback);
        };
        UpdateMeeting: GrpcUnaryServiceInterface<UpdateMeetingRequest, dependency_3.google.protobuf.Empty> = (message: UpdateMeetingRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_3.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.UpdateMeeting(message, metadata, options, callback);
        };
        SearchMeetings: GrpcUnaryServiceInterface<SearchMeetingsRequest, SearchMeetingsResponse> = (message: SearchMeetingsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SearchMeetingsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SearchMeetingsResponse>, callback?: grpc_1.requestCallback<SearchMeetingsResponse>): grpc_1.ClientUnaryCall => {
            return super.SearchMeetings(message, metadata, options, callback);
        };
        SearchParticipants: GrpcUnaryServiceInterface<SearchParticipantsRequest, SearchParticipantsResponse> = (message: SearchParticipantsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SearchParticipantsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SearchParticipantsResponse>, callback?: grpc_1.requestCallback<SearchParticipantsResponse>): grpc_1.ClientUnaryCall => {
            return super.SearchParticipants(message, metadata, options, callback);
        };
    }
}
