/**
 * @fileoverview gRPC-Web generated client stub for schedule
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: schedule.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as schedule_pb from './schedule_pb'; // proto import: "schedule.proto"


export class ScheduleServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateMeeting = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/CreateMeeting',
    grpcWeb.MethodType.UNARY,
    schedule_pb.CreateMeetingRequest,
    google_protobuf_empty_pb.Empty,
    (request: schedule_pb.CreateMeetingRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  createMeeting(
    request: schedule_pb.CreateMeetingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  createMeeting(
    request: schedule_pb.CreateMeetingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  createMeeting(
    request: schedule_pb.CreateMeetingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/CreateMeeting',
        request,
        metadata || {},
        this.methodDescriptorCreateMeeting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/CreateMeeting',
    request,
    metadata || {},
    this.methodDescriptorCreateMeeting);
  }

  methodDescriptorUpdateMeeting = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/UpdateMeeting',
    grpcWeb.MethodType.UNARY,
    schedule_pb.UpdateMeetingRequest,
    google_protobuf_empty_pb.Empty,
    (request: schedule_pb.UpdateMeetingRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  updateMeeting(
    request: schedule_pb.UpdateMeetingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  updateMeeting(
    request: schedule_pb.UpdateMeetingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  updateMeeting(
    request: schedule_pb.UpdateMeetingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/UpdateMeeting',
        request,
        metadata || {},
        this.methodDescriptorUpdateMeeting,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/UpdateMeeting',
    request,
    metadata || {},
    this.methodDescriptorUpdateMeeting);
  }

  methodDescriptorSearchMeetings = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/SearchMeetings',
    grpcWeb.MethodType.UNARY,
    schedule_pb.SearchMeetingsRequest,
    schedule_pb.SearchMeetingsResponse,
    (request: schedule_pb.SearchMeetingsRequest) => {
      return request.serializeBinary();
    },
    schedule_pb.SearchMeetingsResponse.deserializeBinary
  );

  searchMeetings(
    request: schedule_pb.SearchMeetingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<schedule_pb.SearchMeetingsResponse>;

  searchMeetings(
    request: schedule_pb.SearchMeetingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: schedule_pb.SearchMeetingsResponse) => void): grpcWeb.ClientReadableStream<schedule_pb.SearchMeetingsResponse>;

  searchMeetings(
    request: schedule_pb.SearchMeetingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: schedule_pb.SearchMeetingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/SearchMeetings',
        request,
        metadata || {},
        this.methodDescriptorSearchMeetings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/SearchMeetings',
    request,
    metadata || {},
    this.methodDescriptorSearchMeetings);
  }

  methodDescriptorSearchParticipants = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/SearchParticipants',
    grpcWeb.MethodType.UNARY,
    schedule_pb.SearchParticipantsRequest,
    schedule_pb.SearchParticipantsResponse,
    (request: schedule_pb.SearchParticipantsRequest) => {
      return request.serializeBinary();
    },
    schedule_pb.SearchParticipantsResponse.deserializeBinary
  );

  searchParticipants(
    request: schedule_pb.SearchParticipantsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<schedule_pb.SearchParticipantsResponse>;

  searchParticipants(
    request: schedule_pb.SearchParticipantsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: schedule_pb.SearchParticipantsResponse) => void): grpcWeb.ClientReadableStream<schedule_pb.SearchParticipantsResponse>;

  searchParticipants(
    request: schedule_pb.SearchParticipantsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: schedule_pb.SearchParticipantsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/SearchParticipants',
        request,
        metadata || {},
        this.methodDescriptorSearchParticipants,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/SearchParticipants',
    request,
    metadata || {},
    this.methodDescriptorSearchParticipants);
  }

}

