// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               unknown
// source: schedule.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "schedule";

export enum MeetingType {
  VIDEO = 0,
  AUDIO = 1,
  UNRECOGNIZED = -1,
}

export function meetingTypeFromJSON(object: any): MeetingType {
  switch (object) {
    case 0:
    case "VIDEO":
      return MeetingType.VIDEO;
    case 1:
    case "AUDIO":
      return MeetingType.AUDIO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MeetingType.UNRECOGNIZED;
  }
}

export function meetingTypeToJSON(object: MeetingType): string {
  switch (object) {
    case MeetingType.VIDEO:
      return "VIDEO";
    case MeetingType.AUDIO:
      return "AUDIO";
    case MeetingType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Meeting {
  id: number;
  title: string;
  description: string;
  type: MeetingType;
  startTime: Date | undefined;
  participantsCount: number;
  host: MeetParticipant | undefined;
  isCancelled: boolean;
  currentuserId: string;
  firstThreeParticipants: MeetParticipant[];
}

export interface MeetParticipant {
  id: string;
  avatarUrl: string;
  name: string;
  email: string;
}

export interface CreateMeetingRequest {
  title: string;
  description: string;
  startTime: Date | undefined;
  type: MeetingType;
  participantIds: string[];
}

export interface UpdateMeetingRequest {
  id: number;
  title?: string | undefined;
  description?: string | undefined;
  startTime?: Date | undefined;
  type?: MeetingType | undefined;
  isParticipantIdsEmpty: boolean;
  participantIds: string[];
  isCancelled?: boolean | undefined;
}

export interface UpdateMeetingResponse {
  meeting: Meeting | undefined;
}

export interface SearchMeetingsRequest {
  query: string;
  category: SearchMeetingsRequest_MeetingCategory;
  lastId?: number | undefined;
  pageSize: number;
}

export enum SearchMeetingsRequest_MeetingCategory {
  ALL = 0,
  PASSED = 1,
  UPCOMING = 2,
  UNRECOGNIZED = -1,
}

export function searchMeetingsRequest_MeetingCategoryFromJSON(object: any): SearchMeetingsRequest_MeetingCategory {
  switch (object) {
    case 0:
    case "ALL":
      return SearchMeetingsRequest_MeetingCategory.ALL;
    case 1:
    case "PASSED":
      return SearchMeetingsRequest_MeetingCategory.PASSED;
    case 2:
    case "UPCOMING":
      return SearchMeetingsRequest_MeetingCategory.UPCOMING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SearchMeetingsRequest_MeetingCategory.UNRECOGNIZED;
  }
}

export function searchMeetingsRequest_MeetingCategoryToJSON(object: SearchMeetingsRequest_MeetingCategory): string {
  switch (object) {
    case SearchMeetingsRequest_MeetingCategory.ALL:
      return "ALL";
    case SearchMeetingsRequest_MeetingCategory.PASSED:
      return "PASSED";
    case SearchMeetingsRequest_MeetingCategory.UPCOMING:
      return "UPCOMING";
    case SearchMeetingsRequest_MeetingCategory.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SearchMeetingsResponse {
  meetings: Meeting[];
}

export interface SearchParticipantsRequest {
  emailQuery: string;
  lastId?: string | undefined;
  pageSize: number;
}

export interface SearchParticipantsResponse {
  participants: MeetParticipant[];
}

export interface GetMeetingRequest {
  id: number;
}

function createBaseMeeting(): Meeting {
  return {
    id: 0,
    title: "",
    description: "",
    type: 0,
    startTime: undefined,
    participantsCount: 0,
    host: undefined,
    isCancelled: false,
    currentuserId: "",
    firstThreeParticipants: [],
  };
}

export const Meeting: MessageFns<Meeting> = {
  encode(message: Meeting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(42).fork()).join();
    }
    if (message.participantsCount !== 0) {
      writer.uint32(48).uint32(message.participantsCount);
    }
    if (message.host !== undefined) {
      MeetParticipant.encode(message.host, writer.uint32(58).fork()).join();
    }
    if (message.isCancelled !== false) {
      writer.uint32(64).bool(message.isCancelled);
    }
    if (message.currentuserId !== "") {
      writer.uint32(82).string(message.currentuserId);
    }
    for (const v of message.firstThreeParticipants) {
      MeetParticipant.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Meeting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeeting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.participantsCount = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.host = MeetParticipant.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isCancelled = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.currentuserId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.firstThreeParticipants.push(MeetParticipant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Meeting {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      type: isSet(object.type) ? meetingTypeFromJSON(object.type) : 0,
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      participantsCount: isSet(object.participantsCount) ? globalThis.Number(object.participantsCount) : 0,
      host: isSet(object.host) ? MeetParticipant.fromJSON(object.host) : undefined,
      isCancelled: isSet(object.isCancelled) ? globalThis.Boolean(object.isCancelled) : false,
      currentuserId: isSet(object.currentuserId) ? globalThis.String(object.currentuserId) : "",
      firstThreeParticipants: globalThis.Array.isArray(object?.firstThreeParticipants)
        ? object.firstThreeParticipants.map((e: any) => MeetParticipant.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Meeting): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.type !== 0) {
      obj.type = meetingTypeToJSON(message.type);
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.participantsCount !== 0) {
      obj.participantsCount = Math.round(message.participantsCount);
    }
    if (message.host !== undefined) {
      obj.host = MeetParticipant.toJSON(message.host);
    }
    if (message.isCancelled !== false) {
      obj.isCancelled = message.isCancelled;
    }
    if (message.currentuserId !== "") {
      obj.currentuserId = message.currentuserId;
    }
    if (message.firstThreeParticipants?.length) {
      obj.firstThreeParticipants = message.firstThreeParticipants.map((e) => MeetParticipant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Meeting>): Meeting {
    return Meeting.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Meeting>): Meeting {
    const message = createBaseMeeting();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.type = object.type ?? 0;
    message.startTime = object.startTime ?? undefined;
    message.participantsCount = object.participantsCount ?? 0;
    message.host = (object.host !== undefined && object.host !== null)
      ? MeetParticipant.fromPartial(object.host)
      : undefined;
    message.isCancelled = object.isCancelled ?? false;
    message.currentuserId = object.currentuserId ?? "";
    message.firstThreeParticipants = object.firstThreeParticipants?.map((e) => MeetParticipant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMeetParticipant(): MeetParticipant {
  return { id: "", avatarUrl: "", name: "", email: "" };
}

export const MeetParticipant: MessageFns<MeetParticipant> = {
  encode(message: MeetParticipant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    if (message.avatarUrl !== "") {
      writer.uint32(26).string(message.avatarUrl);
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(42).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MeetParticipant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeetParticipant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatarUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MeetParticipant {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      avatarUrl: isSet(object.avatarUrl) ? globalThis.String(object.avatarUrl) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: MeetParticipant): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.avatarUrl !== "") {
      obj.avatarUrl = message.avatarUrl;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create(base?: DeepPartial<MeetParticipant>): MeetParticipant {
    return MeetParticipant.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MeetParticipant>): MeetParticipant {
    const message = createBaseMeetParticipant();
    message.id = object.id ?? "";
    message.avatarUrl = object.avatarUrl ?? "";
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseCreateMeetingRequest(): CreateMeetingRequest {
  return { title: "", description: "", startTime: undefined, type: 0, participantIds: [] };
}

export const CreateMeetingRequest: MessageFns<CreateMeetingRequest> = {
  encode(message: CreateMeetingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(26).fork()).join();
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    for (const v of message.participantIds) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateMeetingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateMeetingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.participantIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateMeetingRequest {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      type: isSet(object.type) ? meetingTypeFromJSON(object.type) : 0,
      participantIds: globalThis.Array.isArray(object?.participantIds)
        ? object.participantIds.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CreateMeetingRequest): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.type !== 0) {
      obj.type = meetingTypeToJSON(message.type);
    }
    if (message.participantIds?.length) {
      obj.participantIds = message.participantIds;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateMeetingRequest>): CreateMeetingRequest {
    return CreateMeetingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateMeetingRequest>): CreateMeetingRequest {
    const message = createBaseCreateMeetingRequest();
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.startTime = object.startTime ?? undefined;
    message.type = object.type ?? 0;
    message.participantIds = object.participantIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseUpdateMeetingRequest(): UpdateMeetingRequest {
  return {
    id: 0,
    title: undefined,
    description: undefined,
    startTime: undefined,
    type: undefined,
    isParticipantIdsEmpty: false,
    participantIds: [],
    isCancelled: undefined,
  };
}

export const UpdateMeetingRequest: MessageFns<UpdateMeetingRequest> = {
  encode(message: UpdateMeetingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.title !== undefined) {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(34).fork()).join();
    }
    if (message.type !== undefined) {
      writer.uint32(40).int32(message.type);
    }
    if (message.isParticipantIdsEmpty !== false) {
      writer.uint32(48).bool(message.isParticipantIdsEmpty);
    }
    for (const v of message.participantIds) {
      writer.uint32(58).string(v!);
    }
    if (message.isCancelled !== undefined) {
      writer.uint32(64).bool(message.isCancelled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMeetingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMeetingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isParticipantIdsEmpty = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.participantIds.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isCancelled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMeetingRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : undefined,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      type: isSet(object.type) ? meetingTypeFromJSON(object.type) : undefined,
      isParticipantIdsEmpty: isSet(object.isParticipantIdsEmpty)
        ? globalThis.Boolean(object.isParticipantIdsEmpty)
        : false,
      participantIds: globalThis.Array.isArray(object?.participantIds)
        ? object.participantIds.map((e: any) => globalThis.String(e))
        : [],
      isCancelled: isSet(object.isCancelled) ? globalThis.Boolean(object.isCancelled) : undefined,
    };
  },

  toJSON(message: UpdateMeetingRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== undefined) {
      obj.title = message.title;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.type !== undefined) {
      obj.type = meetingTypeToJSON(message.type);
    }
    if (message.isParticipantIdsEmpty !== false) {
      obj.isParticipantIdsEmpty = message.isParticipantIdsEmpty;
    }
    if (message.participantIds?.length) {
      obj.participantIds = message.participantIds;
    }
    if (message.isCancelled !== undefined) {
      obj.isCancelled = message.isCancelled;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateMeetingRequest>): UpdateMeetingRequest {
    return UpdateMeetingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateMeetingRequest>): UpdateMeetingRequest {
    const message = createBaseUpdateMeetingRequest();
    message.id = object.id ?? 0;
    message.title = object.title ?? undefined;
    message.description = object.description ?? undefined;
    message.startTime = object.startTime ?? undefined;
    message.type = object.type ?? undefined;
    message.isParticipantIdsEmpty = object.isParticipantIdsEmpty ?? false;
    message.participantIds = object.participantIds?.map((e) => e) || [];
    message.isCancelled = object.isCancelled ?? undefined;
    return message;
  },
};

function createBaseUpdateMeetingResponse(): UpdateMeetingResponse {
  return { meeting: undefined };
}

export const UpdateMeetingResponse: MessageFns<UpdateMeetingResponse> = {
  encode(message: UpdateMeetingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meeting !== undefined) {
      Meeting.encode(message.meeting, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMeetingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMeetingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meeting = Meeting.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMeetingResponse {
    return { meeting: isSet(object.meeting) ? Meeting.fromJSON(object.meeting) : undefined };
  },

  toJSON(message: UpdateMeetingResponse): unknown {
    const obj: any = {};
    if (message.meeting !== undefined) {
      obj.meeting = Meeting.toJSON(message.meeting);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateMeetingResponse>): UpdateMeetingResponse {
    return UpdateMeetingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateMeetingResponse>): UpdateMeetingResponse {
    const message = createBaseUpdateMeetingResponse();
    message.meeting = (object.meeting !== undefined && object.meeting !== null)
      ? Meeting.fromPartial(object.meeting)
      : undefined;
    return message;
  },
};

function createBaseSearchMeetingsRequest(): SearchMeetingsRequest {
  return { query: "", category: 0, lastId: undefined, pageSize: 0 };
}

export const SearchMeetingsRequest: MessageFns<SearchMeetingsRequest> = {
  encode(message: SearchMeetingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.category !== 0) {
      writer.uint32(32).int32(message.category);
    }
    if (message.lastId !== undefined) {
      writer.uint32(40).uint32(message.lastId);
    }
    if (message.pageSize !== 0) {
      writer.uint32(48).uint32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchMeetingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchMeetingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.category = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastId = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pageSize = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchMeetingsRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      category: isSet(object.category) ? searchMeetingsRequest_MeetingCategoryFromJSON(object.category) : 0,
      lastId: isSet(object.lastId) ? globalThis.Number(object.lastId) : undefined,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
    };
  },

  toJSON(message: SearchMeetingsRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.category !== 0) {
      obj.category = searchMeetingsRequest_MeetingCategoryToJSON(message.category);
    }
    if (message.lastId !== undefined) {
      obj.lastId = Math.round(message.lastId);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create(base?: DeepPartial<SearchMeetingsRequest>): SearchMeetingsRequest {
    return SearchMeetingsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchMeetingsRequest>): SearchMeetingsRequest {
    const message = createBaseSearchMeetingsRequest();
    message.query = object.query ?? "";
    message.category = object.category ?? 0;
    message.lastId = object.lastId ?? undefined;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseSearchMeetingsResponse(): SearchMeetingsResponse {
  return { meetings: [] };
}

export const SearchMeetingsResponse: MessageFns<SearchMeetingsResponse> = {
  encode(message: SearchMeetingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.meetings) {
      Meeting.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchMeetingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchMeetingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meetings.push(Meeting.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchMeetingsResponse {
    return {
      meetings: globalThis.Array.isArray(object?.meetings) ? object.meetings.map((e: any) => Meeting.fromJSON(e)) : [],
    };
  },

  toJSON(message: SearchMeetingsResponse): unknown {
    const obj: any = {};
    if (message.meetings?.length) {
      obj.meetings = message.meetings.map((e) => Meeting.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SearchMeetingsResponse>): SearchMeetingsResponse {
    return SearchMeetingsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchMeetingsResponse>): SearchMeetingsResponse {
    const message = createBaseSearchMeetingsResponse();
    message.meetings = object.meetings?.map((e) => Meeting.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSearchParticipantsRequest(): SearchParticipantsRequest {
  return { emailQuery: "", lastId: undefined, pageSize: 0 };
}

export const SearchParticipantsRequest: MessageFns<SearchParticipantsRequest> = {
  encode(message: SearchParticipantsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.emailQuery !== "") {
      writer.uint32(10).string(message.emailQuery);
    }
    if (message.lastId !== undefined) {
      writer.uint32(18).string(message.lastId);
    }
    if (message.pageSize !== 0) {
      writer.uint32(24).uint32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchParticipantsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchParticipantsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.emailQuery = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pageSize = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchParticipantsRequest {
    return {
      emailQuery: isSet(object.emailQuery) ? globalThis.String(object.emailQuery) : "",
      lastId: isSet(object.lastId) ? globalThis.String(object.lastId) : undefined,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
    };
  },

  toJSON(message: SearchParticipantsRequest): unknown {
    const obj: any = {};
    if (message.emailQuery !== "") {
      obj.emailQuery = message.emailQuery;
    }
    if (message.lastId !== undefined) {
      obj.lastId = message.lastId;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create(base?: DeepPartial<SearchParticipantsRequest>): SearchParticipantsRequest {
    return SearchParticipantsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchParticipantsRequest>): SearchParticipantsRequest {
    const message = createBaseSearchParticipantsRequest();
    message.emailQuery = object.emailQuery ?? "";
    message.lastId = object.lastId ?? undefined;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseSearchParticipantsResponse(): SearchParticipantsResponse {
  return { participants: [] };
}

export const SearchParticipantsResponse: MessageFns<SearchParticipantsResponse> = {
  encode(message: SearchParticipantsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.participants) {
      MeetParticipant.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchParticipantsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchParticipantsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.participants.push(MeetParticipant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchParticipantsResponse {
    return {
      participants: globalThis.Array.isArray(object?.participants)
        ? object.participants.map((e: any) => MeetParticipant.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SearchParticipantsResponse): unknown {
    const obj: any = {};
    if (message.participants?.length) {
      obj.participants = message.participants.map((e) => MeetParticipant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SearchParticipantsResponse>): SearchParticipantsResponse {
    return SearchParticipantsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchParticipantsResponse>): SearchParticipantsResponse {
    const message = createBaseSearchParticipantsResponse();
    message.participants = object.participants?.map((e) => MeetParticipant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetMeetingRequest(): GetMeetingRequest {
  return { id: 0 };
}

export const GetMeetingRequest: MessageFns<GetMeetingRequest> = {
  encode(message: GetMeetingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMeetingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMeetingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMeetingRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetMeetingRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<GetMeetingRequest>): GetMeetingRequest {
    return GetMeetingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetMeetingRequest>): GetMeetingRequest {
    const message = createBaseGetMeetingRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

export type ScheduleServiceDefinition = typeof ScheduleServiceDefinition;
export const ScheduleServiceDefinition = {
  name: "ScheduleService",
  fullName: "schedule.ScheduleService",
  methods: {
    createMeeting: {
      name: "CreateMeeting",
      requestType: CreateMeetingRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    updateMeeting: {
      name: "UpdateMeeting",
      requestType: UpdateMeetingRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    getMeeting: {
      name: "GetMeeting",
      requestType: GetMeetingRequest,
      requestStream: false,
      responseType: Meeting,
      responseStream: false,
      options: {},
    },
    searchMeetings: {
      name: "SearchMeetings",
      requestType: SearchMeetingsRequest,
      requestStream: false,
      responseType: SearchMeetingsResponse,
      responseStream: false,
      options: {},
    },
    searchParticipants: {
      name: "SearchParticipants",
      requestType: SearchParticipantsRequest,
      requestStream: false,
      responseType: SearchParticipantsResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface ScheduleServiceImplementation<CallContextExt = {}> {
  createMeeting(request: CreateMeetingRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  updateMeeting(request: UpdateMeetingRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  getMeeting(request: GetMeetingRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Meeting>>;
  searchMeetings(
    request: SearchMeetingsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SearchMeetingsResponse>>;
  searchParticipants(
    request: SearchParticipantsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SearchParticipantsResponse>>;
}

export interface ScheduleServiceClient<CallOptionsExt = {}> {
  createMeeting(request: DeepPartial<CreateMeetingRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  updateMeeting(request: DeepPartial<UpdateMeetingRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  getMeeting(request: DeepPartial<GetMeetingRequest>, options?: CallOptions & CallOptionsExt): Promise<Meeting>;
  searchMeetings(
    request: DeepPartial<SearchMeetingsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SearchMeetingsResponse>;
  searchParticipants(
    request: DeepPartial<SearchParticipantsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SearchParticipantsResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
