// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schedule.proto

package __

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeetingType int32

const (
	MeetingType_VIDEO MeetingType = 0
	MeetingType_AUDIO MeetingType = 1
)

// Enum value maps for MeetingType.
var (
	MeetingType_name = map[int32]string{
		0: "VIDEO",
		1: "AUDIO",
	}
	MeetingType_value = map[string]int32{
		"VIDEO": 0,
		"AUDIO": 1,
	}
)

func (x MeetingType) Enum() *MeetingType {
	p := new(MeetingType)
	*p = x
	return p
}

func (x MeetingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingType) Descriptor() protoreflect.EnumDescriptor {
	return file_schedule_proto_enumTypes[0].Descriptor()
}

func (MeetingType) Type() protoreflect.EnumType {
	return &file_schedule_proto_enumTypes[0]
}

func (x MeetingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingType.Descriptor instead.
func (MeetingType) EnumDescriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{0}
}

type SearchMeetingsRequest_MeetingCategory int32

const (
	SearchMeetingsRequest_ALL      SearchMeetingsRequest_MeetingCategory = 0
	SearchMeetingsRequest_PASSED   SearchMeetingsRequest_MeetingCategory = 1
	SearchMeetingsRequest_UPCOMING SearchMeetingsRequest_MeetingCategory = 2
)

// Enum value maps for SearchMeetingsRequest_MeetingCategory.
var (
	SearchMeetingsRequest_MeetingCategory_name = map[int32]string{
		0: "ALL",
		1: "PASSED",
		2: "UPCOMING",
	}
	SearchMeetingsRequest_MeetingCategory_value = map[string]int32{
		"ALL":      0,
		"PASSED":   1,
		"UPCOMING": 2,
	}
)

func (x SearchMeetingsRequest_MeetingCategory) Enum() *SearchMeetingsRequest_MeetingCategory {
	p := new(SearchMeetingsRequest_MeetingCategory)
	*p = x
	return p
}

func (x SearchMeetingsRequest_MeetingCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMeetingsRequest_MeetingCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_schedule_proto_enumTypes[1].Descriptor()
}

func (SearchMeetingsRequest_MeetingCategory) Type() protoreflect.EnumType {
	return &file_schedule_proto_enumTypes[1]
}

func (x SearchMeetingsRequest_MeetingCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMeetingsRequest_MeetingCategory.Descriptor instead.
func (SearchMeetingsRequest_MeetingCategory) EnumDescriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{5, 0}
}

type Meeting struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                   MeetingType            `protobuf:"varint,4,opt,name=type,proto3,enum=schedule.MeetingType" json:"type,omitempty"`
	StartTime              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ParticipantsCount      uint32                 `protobuf:"varint,6,opt,name=participants_count,json=participantsCount,proto3" json:"participants_count,omitempty"`
	Host                   *MeetParticipant       `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	IsCancelled            bool                   `protobuf:"varint,8,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	CurrentUserId          string                 `protobuf:"bytes,10,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	FirstThreeParticipants []*MeetParticipant     `protobuf:"bytes,9,rep,name=first_three_participants,json=firstThreeParticipants,proto3" json:"first_three_participants,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Meeting) Reset() {
	*x = Meeting{}
	mi := &file_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meeting) ProtoMessage() {}

func (x *Meeting) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meeting.ProtoReflect.Descriptor instead.
func (*Meeting) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Meeting) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Meeting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Meeting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meeting) GetType() MeetingType {
	if x != nil {
		return x.Type
	}
	return MeetingType_VIDEO
}

func (x *Meeting) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Meeting) GetParticipantsCount() uint32 {
	if x != nil {
		return x.ParticipantsCount
	}
	return 0
}

func (x *Meeting) GetHost() *MeetParticipant {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Meeting) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *Meeting) GetCurrentUserId() string {
	if x != nil {
		return x.CurrentUserId
	}
	return ""
}

func (x *Meeting) GetFirstThreeParticipants() []*MeetParticipant {
	if x != nil {
		return x.FirstThreeParticipants
	}
	return nil
}

type MeetParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetParticipant) Reset() {
	*x = MeetParticipant{}
	mi := &file_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetParticipant) ProtoMessage() {}

func (x *MeetParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetParticipant.ProtoReflect.Descriptor instead.
func (*MeetParticipant) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *MeetParticipant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeetParticipant) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *MeetParticipant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeetParticipant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateMeetingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Type           MeetingType            `protobuf:"varint,4,opt,name=type,proto3,enum=schedule.MeetingType" json:"type,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,5,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	mi := &file_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMeetingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMeetingRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateMeetingRequest) GetType() MeetingType {
	if x != nil {
		return x.Type
	}
	return MeetingType_VIDEO
}

func (x *CreateMeetingRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type UpdateMeetingRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                 *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description           *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StartTime             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	Type                  *MeetingType           `protobuf:"varint,5,opt,name=type,proto3,enum=schedule.MeetingType,oneof" json:"type,omitempty"`
	IsParticipantIdsEmpty bool                   `protobuf:"varint,6,opt,name=isParticipantIdsEmpty,proto3" json:"isParticipantIdsEmpty,omitempty"`
	ParticipantIds        []string               `protobuf:"bytes,7,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	IsCancelled           *bool                  `protobuf:"varint,8,opt,name=is_cancelled,json=isCancelled,proto3,oneof" json:"is_cancelled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateMeetingRequest) Reset() {
	*x = UpdateMeetingRequest{}
	mi := &file_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRequest) ProtoMessage() {}

func (x *UpdateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMeetingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMeetingRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateMeetingRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMeetingRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateMeetingRequest) GetType() MeetingType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MeetingType_VIDEO
}

func (x *UpdateMeetingRequest) GetIsParticipantIdsEmpty() bool {
	if x != nil {
		return x.IsParticipantIdsEmpty
	}
	return false
}

func (x *UpdateMeetingRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *UpdateMeetingRequest) GetIsCancelled() bool {
	if x != nil && x.IsCancelled != nil {
		return *x.IsCancelled
	}
	return false
}

type UpdateMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *Meeting               `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingResponse) Reset() {
	*x = UpdateMeetingResponse{}
	mi := &file_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingResponse) ProtoMessage() {}

func (x *UpdateMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeetingResponse) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMeetingResponse) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type SearchMeetingsRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Query         string                                `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      SearchMeetingsRequest_MeetingCategory `protobuf:"varint,4,opt,name=category,proto3,enum=schedule.SearchMeetingsRequest_MeetingCategory" json:"category,omitempty"`
	LastId        *uint32                               `protobuf:"varint,5,opt,name=last_id,json=lastId,proto3,oneof" json:"last_id,omitempty"`
	PageSize      uint32                                `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMeetingsRequest) Reset() {
	*x = SearchMeetingsRequest{}
	mi := &file_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeetingsRequest) ProtoMessage() {}

func (x *SearchMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeetingsRequest.ProtoReflect.Descriptor instead.
func (*SearchMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *SearchMeetingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMeetingsRequest) GetCategory() SearchMeetingsRequest_MeetingCategory {
	if x != nil {
		return x.Category
	}
	return SearchMeetingsRequest_ALL
}

func (x *SearchMeetingsRequest) GetLastId() uint32 {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return 0
}

func (x *SearchMeetingsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchMeetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetings      []*Meeting             `protobuf:"bytes,1,rep,name=meetings,proto3" json:"meetings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMeetingsResponse) Reset() {
	*x = SearchMeetingsResponse{}
	mi := &file_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeetingsResponse) ProtoMessage() {}

func (x *SearchMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeetingsResponse.ProtoReflect.Descriptor instead.
func (*SearchMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *SearchMeetingsResponse) GetMeetings() []*Meeting {
	if x != nil {
		return x.Meetings
	}
	return nil
}

type SearchParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailQuery    string                 `protobuf:"bytes,1,opt,name=emailQuery,proto3" json:"emailQuery,omitempty"`
	LastId        *string                `protobuf:"bytes,2,opt,name=last_id,json=lastId,proto3,oneof" json:"last_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchParticipantsRequest) Reset() {
	*x = SearchParticipantsRequest{}
	mi := &file_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParticipantsRequest) ProtoMessage() {}

func (x *SearchParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParticipantsRequest.ProtoReflect.Descriptor instead.
func (*SearchParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *SearchParticipantsRequest) GetEmailQuery() string {
	if x != nil {
		return x.EmailQuery
	}
	return ""
}

func (x *SearchParticipantsRequest) GetLastId() string {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return ""
}

func (x *SearchParticipantsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*MeetParticipant     `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchParticipantsResponse) Reset() {
	*x = SearchParticipantsResponse{}
	mi := &file_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParticipantsResponse) ProtoMessage() {}

func (x *SearchParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParticipantsResponse.ProtoReflect.Descriptor instead.
func (*SearchParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *SearchParticipantsResponse) GetParticipants() []*MeetParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type GetMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	mi := &file_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeetingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_schedule_proto protoreflect.FileDescriptor

const file_schedule_proto_rawDesc = "" +
	"\n" +
	"\x0eschedule.proto\x12\bschedule\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb5\x03\n" +
	"\aMeeting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.schedule.MeetingTypeR\x04type\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12-\n" +
	"\x12participants_count\x18\x06 \x01(\rR\x11participantsCount\x12-\n" +
	"\x04host\x18\a \x01(\v2\x19.schedule.MeetParticipantR\x04host\x12!\n" +
	"\fis_cancelled\x18\b \x01(\bR\visCancelled\x12&\n" +
	"\x0fcurrent_user_id\x18\n" +
	" \x01(\tR\rcurrentUserId\x12S\n" +
	"\x18first_three_participants\x18\t \x03(\v2\x19.schedule.MeetParticipantR\x16firstThreeParticipants\"j\n" +
	"\x0fMeetParticipant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x8d\x02\n" +
	"\x14CreateMeetingRequest\x12\x1c\n" +
	"\x05title\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12F\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02@\x01R\tstartTime\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.schedule.MeetingTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x128\n" +
	"\x0fparticipant_ids\x18\x05 \x03(\tB\x0f\xbaH\f\x92\x01\t\x18\x01\"\x05r\x03\xb0\x01\x01R\x0eparticipantIds\"\xe1\x03\n" +
	"\x14UpdateMeetingRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06\xbaH\x03\xc8\x01\x01R\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\x05title\x88\x01\x01\x12.\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x01R\vdescription\x88\x01\x01\x12H\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01H\x02R\tstartTime\x88\x01\x01\x128\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.schedule.MeetingTypeB\b\xbaH\x05\x82\x01\x02\x10\x01H\x03R\x04type\x88\x01\x01\x124\n" +
	"\x15isParticipantIdsEmpty\x18\x06 \x01(\bR\x15isParticipantIdsEmpty\x128\n" +
	"\x0fparticipant_ids\x18\a \x03(\tB\x0f\xbaH\f\x92\x01\t\x18\x01\"\x05r\x03\xb0\x01\x01R\x0eparticipantIds\x12&\n" +
	"\fis_cancelled\x18\b \x01(\bH\x04R\visCancelled\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_start_timeB\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_is_cancelled\"D\n" +
	"\x15UpdateMeetingResponse\x12+\n" +
	"\ameeting\x18\x01 \x01(\v2\x11.schedule.MeetingR\ameeting\"\x81\x02\n" +
	"\x15SearchMeetingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12U\n" +
	"\bcategory\x18\x04 \x01(\x0e2/.schedule.SearchMeetingsRequest.MeetingCategoryB\b\xbaH\x05\x82\x01\x02\x10\x01R\bcategory\x12\x1c\n" +
	"\alast_id\x18\x05 \x01(\rH\x00R\x06lastId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\rR\bpageSize\"4\n" +
	"\x0fMeetingCategory\x12\a\n" +
	"\x03ALL\x10\x00\x12\n" +
	"\n" +
	"\x06PASSED\x10\x01\x12\f\n" +
	"\bUPCOMING\x10\x02B\n" +
	"\n" +
	"\b_last_id\"G\n" +
	"\x16SearchMeetingsResponse\x12-\n" +
	"\bmeetings\x18\x01 \x03(\v2\x11.schedule.MeetingR\bmeetings\"\x82\x01\n" +
	"\x19SearchParticipantsRequest\x12\x1e\n" +
	"\n" +
	"emailQuery\x18\x01 \x01(\tR\n" +
	"emailQuery\x12\x1c\n" +
	"\alast_id\x18\x02 \x01(\tH\x00R\x06lastId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSizeB\n" +
	"\n" +
	"\b_last_id\"[\n" +
	"\x1aSearchParticipantsResponse\x12=\n" +
	"\fparticipants\x18\x01 \x03(\v2\x19.schedule.MeetParticipantR\fparticipants\"+\n" +
	"\x11GetMeetingRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06\xbaH\x03\xc8\x01\x01R\x02id*#\n" +
	"\vMeetingType\x12\t\n" +
	"\x05VIDEO\x10\x00\x12\t\n" +
	"\x05AUDIO\x10\x012\x97\x03\n" +
	"\x0fScheduleService\x12G\n" +
	"\rCreateMeeting\x12\x1e.schedule.CreateMeetingRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rUpdateMeeting\x12\x1e.schedule.UpdateMeetingRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"GetMeeting\x12\x1b.schedule.GetMeetingRequest\x1a\x11.schedule.Meeting\x12S\n" +
	"\x0eSearchMeetings\x12\x1f.schedule.SearchMeetingsRequest\x1a .schedule.SearchMeetingsResponse\x12_\n" +
	"\x12SearchParticipants\x12#.schedule.SearchParticipantsRequest\x1a$.schedule.SearchParticipantsResponseB\x03Z\x01.b\x06proto3"

var (
	file_schedule_proto_rawDescOnce sync.Once
	file_schedule_proto_rawDescData []byte
)

func file_schedule_proto_rawDescGZIP() []byte {
	file_schedule_proto_rawDescOnce.Do(func() {
		file_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schedule_proto_rawDesc), len(file_schedule_proto_rawDesc)))
	})
	return file_schedule_proto_rawDescData
}

var file_schedule_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_schedule_proto_goTypes = []any{
	(MeetingType)(0), // 0: schedule.MeetingType
	(SearchMeetingsRequest_MeetingCategory)(0), // 1: schedule.SearchMeetingsRequest.MeetingCategory
	(*Meeting)(nil),                    // 2: schedule.Meeting
	(*MeetParticipant)(nil),            // 3: schedule.MeetParticipant
	(*CreateMeetingRequest)(nil),       // 4: schedule.CreateMeetingRequest
	(*UpdateMeetingRequest)(nil),       // 5: schedule.UpdateMeetingRequest
	(*UpdateMeetingResponse)(nil),      // 6: schedule.UpdateMeetingResponse
	(*SearchMeetingsRequest)(nil),      // 7: schedule.SearchMeetingsRequest
	(*SearchMeetingsResponse)(nil),     // 8: schedule.SearchMeetingsResponse
	(*SearchParticipantsRequest)(nil),  // 9: schedule.SearchParticipantsRequest
	(*SearchParticipantsResponse)(nil), // 10: schedule.SearchParticipantsResponse
	(*GetMeetingRequest)(nil),          // 11: schedule.GetMeetingRequest
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_schedule_proto_depIdxs = []int32{
	0,  // 0: schedule.Meeting.type:type_name -> schedule.MeetingType
	12, // 1: schedule.Meeting.start_time:type_name -> google.protobuf.Timestamp
	3,  // 2: schedule.Meeting.host:type_name -> schedule.MeetParticipant
	3,  // 3: schedule.Meeting.first_three_participants:type_name -> schedule.MeetParticipant
	12, // 4: schedule.CreateMeetingRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 5: schedule.CreateMeetingRequest.type:type_name -> schedule.MeetingType
	12, // 6: schedule.UpdateMeetingRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 7: schedule.UpdateMeetingRequest.type:type_name -> schedule.MeetingType
	2,  // 8: schedule.UpdateMeetingResponse.meeting:type_name -> schedule.Meeting
	1,  // 9: schedule.SearchMeetingsRequest.category:type_name -> schedule.SearchMeetingsRequest.MeetingCategory
	2,  // 10: schedule.SearchMeetingsResponse.meetings:type_name -> schedule.Meeting
	3,  // 11: schedule.SearchParticipantsResponse.participants:type_name -> schedule.MeetParticipant
	4,  // 12: schedule.ScheduleService.CreateMeeting:input_type -> schedule.CreateMeetingRequest
	5,  // 13: schedule.ScheduleService.UpdateMeeting:input_type -> schedule.UpdateMeetingRequest
	11, // 14: schedule.ScheduleService.GetMeeting:input_type -> schedule.GetMeetingRequest
	7,  // 15: schedule.ScheduleService.SearchMeetings:input_type -> schedule.SearchMeetingsRequest
	9,  // 16: schedule.ScheduleService.SearchParticipants:input_type -> schedule.SearchParticipantsRequest
	13, // 17: schedule.ScheduleService.CreateMeeting:output_type -> google.protobuf.Empty
	13, // 18: schedule.ScheduleService.UpdateMeeting:output_type -> google.protobuf.Empty
	2,  // 19: schedule.ScheduleService.GetMeeting:output_type -> schedule.Meeting
	8,  // 20: schedule.ScheduleService.SearchMeetings:output_type -> schedule.SearchMeetingsResponse
	10, // 21: schedule.ScheduleService.SearchParticipants:output_type -> schedule.SearchParticipantsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_schedule_proto_init() }
func file_schedule_proto_init() {
	if File_schedule_proto != nil {
		return
	}
	file_schedule_proto_msgTypes[3].OneofWrappers = []any{}
	file_schedule_proto_msgTypes[5].OneofWrappers = []any{}
	file_schedule_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schedule_proto_rawDesc), len(file_schedule_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schedule_proto_goTypes,
		DependencyIndexes: file_schedule_proto_depIdxs,
		EnumInfos:         file_schedule_proto_enumTypes,
		MessageInfos:      file_schedule_proto_msgTypes,
	}.Build()
	File_schedule_proto = out.File
	file_schedule_proto_goTypes = nil
	file_schedule_proto_depIdxs = nil
}
